Added setup to clocksource

diff --git a/scripts/configure-clocksource/configure b/scripts/configure-clocksource/configure
--- a/scripts/configure-clocksource/configure
+++ b/scripts/configure-clocksource/configure
@@ -20,8 +20,21 @@
 # For more information on the Alces Clusterware, please visit:
 # https://github.com/alces-software/clusterware
 #==============================================================================
-require clocksource
-require files
+setup() {
+    local a xdg_config
+    IFS=: read -a xdg_config <<< "${XDG_CONFIG_HOME:-$HOME/.config}:${XDG_CONFIG_DIRS:-/etc/xdg}"
+    for a in "${xdg_config[@]}"; do
+        if [ -e "${a}"/clusterware/config.rc ]; then
+            source "${a}"/clusterware/config.rc
+            break
+        fi
+    done
+    if [ -z "${cw_ROOT}" ]; then
+        echo "$0: unable to locate clusterware configuration"
+        exit 1
+    fi
+    kernel_load
+}
 
 main() {
     local temp_file
@@ -41,5 +54,10 @@ main() {
         clocksource_set $cw_CLUSTER_clocksource
     fi
 }
+
+setup
+
+require clocksource
+require files
 
 main
