Start Docker service in system-agnostic way.

diff --git a/scripts/configure-docker/start b/scripts/configure-docker/start
--- a/scripts/configure-docker/start
+++ b/scripts/configure-docker/start
@@ -20,4 +20,28 @@
 # For more information on the Alces Clusterware, please visit:
 # https://github.com/alces-software/clusterware
 #==============================================================================
-systemctl start docker
+
+setup() {
+    local a xdg_config
+    IFS=: read -a xdg_config <<< "${XDG_CONFIG_HOME:-$HOME/.config}:${XDG_CONFIG_DIRS:-/etc/xdg}"
+    for a in "${xdg_config[@]}"; do
+        if [ -e "${a}"/clusterware/config.vars.sh ]; then
+            source "${a}"/clusterware/config.vars.sh
+            break
+        fi
+    done
+    if [ -z "${cw_ROOT}" ]; then
+        echo "$0: unable to locate clusterware configuration"
+        exit 1
+    fi
+    kernel_load
+}
+
+main() {
+  distro_start_service docker
+}
+
+setup
+require distro
+
+main "$@"
